name: Docker

on: [push,pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          tags: rcon2matrix:latest
          load: true

      - name: Save image
        run: docker save -o rcon2matrix.tar rcon2matrix:latest

      - name: Store image
        uses: actions/upload-artifact@v3
        with:
          name: rcon2matrix.tar
          path: rcon2matrix.tar
