name: Lint and Build

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod download && go mod verify

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags="-s -w" -trimpath -v ./...

      - name: Store binary
        uses: actions/upload-artifact@v3
        with:
          name: rcon2matrix
          path: rcon2matrix
